### ISSUE TITLE
Little typo in documentation

### ISSUE THREAD

**Issue by pmouawad** [egaillardon/jmeter#1]
Hello Emmanuel,
Congrats for your project , very easy to use.

I wanted to report a little issue in documentation:

- https://github.com/egaillardon/jmeter#runner-an-interactive-dockerized-client-in-non-gui-mode

the \`pwd\` shows as pwd which leads to an issue when running by just copy/pasting.

Regards

**Comment by egaillardon** [comment]
Hello Philippe,
Thank you for your comments.
The issue will be corrected in the next version  : 5.1.1-1.1.0.
Regards
