### ISSUE TITLE
Repo contains no licence file

### ISSUE THREAD

**Issue by NickGraham101** [egaillardon/jmeter#6]
This repo contains no licence file so the copyright status of the files within it is unclear.  I appreciate that this would not cover the licencing of the software within the images but am considering using this Dockerfile as the basis for some work in my own open source project.  I need to understand the copyright implications before doing so.  Please could you add a licence file or confirm that a licence has been omitted by design.

https://choosealicense.com/no-permission/

**Comment by egaillardon** [comment]
Just added a LICENSE file.
Thanks.
